---
title: Andric Tham
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: andric@nuisance.co
author: Andric Tham
description: Curious about the world. I’m a digital designer who writes about culture
  and technology.
baseurl: ''
url: ''
date_format: "%b %-d, %Y"
google_verification: 
google_analytics: 
google_tag_manager: 
bing_verification: 
animated: true
show_related_posts: true
show_post_footers: true
show_social_icons: true
ajaxify_contact_form: true
enable_mathjax: true
extended_fonts: true
disqus_shortname: 
facebook_comments: true
facebook_appid: 
facebook_comments_number: 10
github_username: andrictham
bitbucket_username: 
stackoverflow_id: 
twitter_username: astralwave
skype_username: 
steam_nickname: 
google_plus_id: 
linkedin_username: 
angellist_username: 
medium_id: andric
bitcoin_url: 
paypal_url: 
flattr_button: 
show_sharing_icons: false
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true
text:
  pagination:
    newer: Newer
    older: Older
  share_buttons:
    text: Share this post!
    facebook: Share on Facebook
    twitter: Share on Twitter
    googleplus: Share on Google+
    linkedin: Share on LinkedIn
    digg: Share on Digg
    tumblr: Share on Tumblr
    reddit: Share on Reddit
    stumbleupon: Share on StumbleUpon
    hackernews: Share on Hacker News
  post:
    updated: Updated
    minute_read: minute read
    related_posts: Related Posts
  index:
    coming_soon: Coming soon...
  contact:
    email: Email Address
    content: What would you like to say?
    subject: New submission!
    submit: Say Hello
    ajax:
      sending: sending..
      sent: Message sent!
      error: Error!
  thanks: Thanks for contacting us. We will reply as soon as possible.
  og_locale: en_US
markdown: kramdown
redcarpet:
  extensions:
  - smart
  - tables
  - with_toc_data
permalink: pretty
paginate: 4
sass:
  compressed: true
gems:
- jekyll-paginate
- jekyll-sitemap
exclude:
- vendor
